D:/1/tools/mkvtoolnix\mkvmerge.exe --ui-language ru --output ^"E:\Аниме\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex [BDRip 1280x690 HEVC FLAC TrueHD]\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex 23 [BDRip 1280x690 HEVC FLAC TrueHD].mkv^" --language 0:jpn --track-name ^"0:BDRip by Urotsuki^" --compression 0:none --timestamps ^"0:G:\GITS SAC\23\timecodes.txt^" ^"^(^" ^"G:\GITS SAC\23\23.hevc^" ^"^)^" --language 0:jpn --track-name ^"0:LPCM-^>FLAC^" --compression 0:none ^"^(^" ^"G:\GITS SAC\23\23.flac^" ^"^)^" --chapter-language und --chapters ^"G:\GITS SAC\23\23.xml^" --track-order 0:0,1:0

D:/1/tools/mkvtoolnix\mkvmerge.exe --ui-language ru --output ^"E:\Аниме\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex [BDRip 1280x690 HEVC FLAC TrueHD]\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex 24 [BDRip 1280x690 HEVC FLAC TrueHD].mkv^" --language 0:jpn --track-name ^"0:BDRip by Urotsuki^" --compression 0:none --timestamps ^"0:G:\GITS SAC\24\timecodes.txt^" ^"^(^" ^"G:\GITS SAC\24\24.hevc^" ^"^)^" --language 0:jpn --track-name ^"0:LPCM-^>FLAC^" --compression 0:none ^"^(^" ^"G:\GITS SAC\24\24.flac^" ^"^)^" --chapter-language und --chapters ^"G:\GITS SAC\24\24.xml^" --track-order 0:0,1:0

D:/1/tools/mkvtoolnix\mkvmerge.exe --ui-language ru --output ^"E:\Аниме\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex [BDRip 1280x690 HEVC FLAC TrueHD]\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex 25 [BDRip 1280x690 HEVC FLAC TrueHD].mkv^" --language 0:jpn --track-name ^"0:BDRip by Urotsuki^" --compression 0:none --timestamps ^"0:G:\GITS SAC\25\timecodes.txt^" ^"^(^" ^"G:\GITS SAC\25\25.hevc^" ^"^)^" --language 0:jpn --track-name ^"0:LPCM-^>FLAC^" --compression 0:none ^"^(^" ^"G:\GITS SAC\25\25.flac^" ^"^)^" --chapter-language und --chapters ^"G:\GITS SAC\25\25.xml^" --track-order 0:0,1:0

D:/1/tools/mkvtoolnix\mkvmerge.exe --ui-language ru --output ^"E:\Аниме\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex [BDRip 1280x690 HEVC FLAC TrueHD]\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex 26 [BDRip 1280x690 HEVC FLAC TrueHD].mkv^" --language 0:jpn --track-name ^"0:BDRip by Urotsuki^" --compression 0:none --timestamps ^"0:G:\GITS SAC\26\timecodes.txt^" ^"^(^" ^"G:\GITS SAC\26\26.hevc^" ^"^)^" --language 0:jpn --track-name ^"0:LPCM-^>FLAC^" --compression 0:none ^"^(^" ^"G:\GITS SAC\26\26.flac^" ^"^)^" --chapter-language und --chapters ^"G:\GITS SAC\26\26.xml^" --track-order 0:0,1:0

D:/1/tools/mkvtoolnix\mkvmerge.exe --ui-language ru --output ^"E:\Аниме\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex [BDRip 1280x690 HEVC FLAC TrueHD]\TrueHD 5.1\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex 23 [BDRip 1280x690 HEVC FLAC TrueHD].mka^" --language 0:jpn --track-name ^"0:Dolby TrueHD 5.1^" --compression 0:none ^"^(^" ^"G:\GITS SAC\23\23.thd^" ^"^)^"

D:/1/tools/mkvtoolnix\mkvmerge.exe --ui-language ru --output ^"E:\Аниме\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex [BDRip 1280x690 HEVC FLAC TrueHD]\TrueHD 5.1\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex 24 [BDRip 1280x690 HEVC FLAC TrueHD].mka^" --language 0:jpn --track-name ^"0:Dolby TrueHD 5.1^" --compression 0:none ^"^(^" ^"G:\GITS SAC\24\24.thd^" ^"^)^"

D:/1/tools/mkvtoolnix\mkvmerge.exe --ui-language ru --output ^"E:\Аниме\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex [BDRip 1280x690 HEVC FLAC TrueHD]\TrueHD 5.1\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex 25 [BDRip 1280x690 HEVC FLAC TrueHD].mka^" --language 0:jpn --track-name ^"0:Dolby TrueHD 5.1^" --compression 0:none ^"^(^" ^"G:\GITS SAC\25\25.thd^" ^"^)^"

D:/1/tools/mkvtoolnix\mkvmerge.exe --ui-language ru --output ^"E:\Аниме\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex [BDRip 1280x690 HEVC FLAC TrueHD]\TrueHD 5.1\[Beatrice-Raws] Ghost in the Shell - Stand Alone Complex 26 [BDRip 1280x690 HEVC FLAC TrueHD].mka^" --language 0:jpn --track-name ^"0:Dolby TrueHD 5.1^" --compression 0:none ^"^(^" ^"G:\GITS SAC\26\26.thd^" ^"^)^"