"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00051.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --amp --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00051.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00053.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --zones 254,5940,b=0.7 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00053.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -




"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00050.vpy - | x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --amp --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 14 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output ""H:\EVA4\bonus\00050.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

@echo off
FOR %%I IN (00027 00035 00036 00037) DO (
.\VapourSynth64-Portable-R55-API4-RC1\vspipe.exe -c y4m %%I.vpy - | x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge -rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 300 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "%%I.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -
)


"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00006.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00006.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00007.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00007.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00008.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00008.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00009.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00009.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00010.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00010.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00011.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00011.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00012.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00012.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00013.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00013.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00014.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00014.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00015.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00015.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00016.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00016.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00017.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00017.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00018.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00018.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00019.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00019.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00020.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00020.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00021.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00021.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00022.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00022.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00023.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00023.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00024.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00024.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00025.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00025.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00026.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00026.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00028.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00028.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00029.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00029.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00030.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00030.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00031.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00031.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00032.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00032.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00033.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00033.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00034.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00034.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00038.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00038.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00039.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00039.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00040.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00040.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00041.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00041.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00042.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00042.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00043.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00043.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00044.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00044.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00045.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00045.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00046.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00046.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00047.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --sao --selective-sao 4 --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --early-skip --tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 16 --b-pyramid --b-adapt 2 --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 16 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00047.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00049.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00049.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00055.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00055.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -

"C:\Program Files\VapourSynth\core\vspipe.exe" -c y4m H:\EVA4\bonus\00056.vpy - | H:\EVA4\2160\x265-x64-v3.5+67-aMod-gcc12.2.1-opt-sandybridge --rect --amp --limit-modes --rskip-edge-threshold 2 --qp-adaptation-range 4 --cu-lossless --limit-modes --limit-refs 1 --rc-lookahead 240 --no-hist-scenecut --no-strong-intra-smoothing --analyze-src-pics -F 16 --open-gop --cbqpoffs -2 --crqpoffs -2 --lookahead-slices 0 --no-cutree --no-early-skip --no-tskip --rskip 1 --rdpenalty 2 --keyint 240 --ref 4 --bframes 11 --b-pyramid --b-adapt 2 --no-sao --aq-mode 3 --aq-strength 1.04 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 4 --me 3 --wpp --subme 7 --crf 15 --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 2.6 --qcomp 0.72 --refine-mv 3 --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "H:\EVA4\bonus\00056.hevc" --csv-log-level 0 --csv "00051.txt" --y4m -
























pause

