.\vaporPortable-r44\vspipe.exe -y 01.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "01.hevc" --csv-log-level 1 --csv "17.txt" --y4m -

.\vaporPortable-r44\vspipe.exe -y 01_720.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode -F 8 --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 6 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 13.8 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "01_720.hevc" --csv-log-level 1 --csv "17_720.txt" --y4m -



.\vaporPortable-r44\vspipe.exe -y 00007.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00007.hevc" --csv-log-level 1 --csv "17.txt" --y4m -

.\vaporPortable-r44\vspipe.exe -y 00008.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00008.hevc" --csv-log-level 1 --csv "17.txt" --y4m -


.\vaporPortable-r44\vspipe.exe -y 00009.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00009.hevc" --csv-log-level 1 --csv "17.txt" --y4m -


.\vaporPortable-r44\vspipe.exe -y 00010.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00010.hevc" --csv-log-level 1 --csv "17.txt" --y4m -

.\vaporPortable-r44\vspipe.exe -y 00011.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00011.hevc" --csv-log-level 1 --csv "17.txt" --y4m -

.\vaporPortable-r44\vspipe.exe -y 00012.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00012.hevc" --csv-log-level 1 --csv "17.txt" --y4m -

.\vaporPortable-r44\vspipe.exe -y 00013.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00013.hevc" --csv-log-level 1 --csv "17.txt" --y4m -

.\vaporPortable-r44\vspipe.exe -y 00014.vpy - | x265-x64-v3.1+8-aMod-gcc911-opt-sandybridge_fix --pmode --hme --hme-search star,umh,umh --hevc-aq --qp-adaptation-range 2 -F 8 --pme --pools "32,32" --limit-modes --open-gop --cbqpoffs -2 --crqpoffs -2 --no-rskip --no-tskip --keyint 240 --no-cutree --ref 4 --bframes 9 --bframe-bias 0 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 4 --aq-strength 0.86 --deblock 1:-1 --tu-intra-depth 2 --tu-inter-depth 2 --me 2 --subme 5 --crf 15 --qcomp 0.72 --b-pyramid --merange 48 --weightp --weightb --rd 4 --psy-rd 2 --rdoq-level 2 --psy-rdoq 4 --sar 1:1 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00014.hevc" --csv-log-level 1 --csv "17.txt" --y4m -



pause
