.\VapourSynth64-Portable-R50\vspipe.exe -y o1.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --qcomp 0.72 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "o1.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y o2.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --qcomp 0.72 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "o2.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y o3.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --qcomp 0.72 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "o3.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y o4.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --qcomp 0.72 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "o4.hevc" --csv-log-level 0 --csv "16.txt" --y4m -


.\VapourSynth64-Portable-R50\vspipe.exe -y M1.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m1.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y M2.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m2.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y M3.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m3.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y M4.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m4.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y M5.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m5.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y M6.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m6.hevc" --csv-log-level 0 --csv "16.txt" --y4m -




.\VapourSynth64-Portable-R50\vspipe.exe -y pv1.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv1.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv2.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 300 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv2.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv3.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 300 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv3.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv4.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 300 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv4.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv5.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 300 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv5.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv7.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 300 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv7.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv8.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 300 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv8.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv9.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 300 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv9.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y t1.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "t1.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y t2.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "t2.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y NCOP.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "NCOP.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y NCED.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --ctu 32 --max-tu-size 16 --qp-adaptation-range 2 --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --no-cutree --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --no-strong-intra-smoothing --aq-strength 1.01 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --qcomp 0.72 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "NCED.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y 26.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --qcomp 0.72 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "26.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y 26.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.02 --qcomp 0.72 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --no-cutree --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 16 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "27.hevc" --csv-log-level 0 --csv "16.txt" --y4m -


pause


