.\VapourSynth64-Portable-R50\vspipe.exe -y NCED.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "NCED.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y NCOP.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "NCOP.hevc" --csv-log-level 0 --csv "16.txt" --y4m -



.\VapourSynth64-Portable-R50\vspipe.exe -y m1.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-cutree --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m1.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y m2.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-cutree --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m2.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y m3.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-cutree --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m3.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y m4.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-cutree --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m4.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y m5.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-cutree --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "m5.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y cm1.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 300 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "cm1.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y cm2.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "cm2.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y cm3.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 300 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "cm3.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y cm4.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 300 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "cm4.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv1.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv1.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv2.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv2.hevc" --csv-log-level 0 --csv "16.txt" --y4m -

.\VapourSynth64-Portable-R50\vspipe.exe -y pv3.vpy - | x265-x64-v3.4+56-aMod-gcc10.2.1-opt-ivybridge --pme --no-strong-intra-smoothing --pmode -F 16 --qp-adaptation-range 2 --open-gop --ctu 32 --max-tu-size 16 --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 1 --keyint 240 --ref 4 --bframes 8 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.03 --deblock 1:-1 --tu-intra-depth 3 --refine-intra 4 --dynamic-refine --tu-inter-depth 3 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "pv3.hevc" --csv-log-level 0 --csv "16.txt" --y4m -
pause


