.\VapourSynth64-Portable-R55-API4-RC1\vspipe.exe -c y4m film1080.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --no-cutree --qp-adaptation-range 4 --no-strong-intra-smoothing --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --lookahead-slices 1 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.02 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "01.hevc" --csv-log-level 0 --csv "01.txt" --y4m -

.\VapourSynth64-Portable-R55-API4-RC1\vspipe.exe -c y4m 00001.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --no-cutree --qp-adaptation-range 4 --no-strong-intra-smoothing --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --lookahead-slices 1 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.02 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00001.hevc" --csv-log-level 0 --csv "01.txt" --y4m -

.\VapourSynth64-Portable-R55-API4-RC1\vspipe.exe -c y4m 00002.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --no-cutree --qp-adaptation-range 4 --no-strong-intra-smoothing --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --lookahead-slices 1 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.02 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00002.hevc" --csv-log-level 0 --csv "01.txt" --y4m -

.\VapourSynth64-Portable-R55-API4-RC1\vspipe.exe -c y4m 00003.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --no-cutree --qp-adaptation-range 4 --no-strong-intra-smoothing --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --lookahead-slices 1 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.02 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00003.hevc" --csv-log-level 0 --csv "01.txt" --y4m -

.\VapourSynth64-Portable-R55-API4-RC1\vspipe.exe -c y4m 00016.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --no-cutree --qp-adaptation-range 4 --no-strong-intra-smoothing --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --lookahead-slices 1 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.02 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00016.hevc" --csv-log-level 0 --csv "01.txt" --y4m -

.\VapourSynth64-Portable-R55-API4-RC1\vspipe.exe -c y4m 00017.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --no-cutree --qp-adaptation-range 4 --no-strong-intra-smoothing --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --lookahead-slices 1 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.02 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00017.hevc" --csv-log-level 0 --csv "01.txt" --y4m -

.\VapourSynth64-Portable-R55-API4-RC1\vspipe.exe -c y4m 00018.vpy - | x265-x64-v3.5+20-aMod-gcc10.2.1-opt-ivybridge --pme --pmode -F 16 --no-cutree --qp-adaptation-range 4 --no-strong-intra-smoothing --open-gop --cbqpoffs -2 --crqpoffs -2 --no-early-skip --rskip 0 --keyint 240 --ref 4 --bframes 8 --lookahead-slices 1 --b-pyramid --b-adapt 2 --no-sao --no-sao-non-deblock --aq-mode 3 --aq-strength 1.02 --deblock 1:-1 --tu-intra-depth 2 --refine-intra 4 --dynamic-refine --tu-inter-depth 2 --me 3 --wpp --subme 7 --crf 15 --b-pyramid --weightp --weightb --rd 5 --rdoq-level 2 --psy-rdoq 4 --psy-rd 2 --refine-mv 3 --analyze-src-pics --temporal-mvp --max-merge 5 --info --colorprim bt709 --transfer bt709 --colormatrix bt709 --output "00018.hevc" --csv-log-level 0 --csv "01.txt" --y4m -






pause


